services:
  marketplace-eureka:
    build:
      dockerfile: ./Dockerfile
      context: ./
    restart: always
    image: marketplace-eureka
    container_name: marketplace-eureka
    volumes:
      - /home/kinoko/logs/marketplace-eureka:/logs
    #      - ./logs:/logs                             # Для отладки на windows машине
    networks:
      - backend
    ports:
      - "33307:33307"

networks:
  backend:
    external: true
