logging:
  config: 'classpath:log4j2.yml'

spring:
  application:
    name: marketplace-eureka

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  dashboard:
    enabled: true
    path: ui

server:
  port: 33307
